### ISSUE TITLE
physics: ClampingScrollPhysics() not working

### ISSUE THREAD

**Issue by sooxt98** [aagarwal1012/Liquid-Pull-To-Refresh#26]
![ezgif-5-be24d7f7f75e](https://user-images.githubusercontent.com/13378059/64421867-30fcdc00-d0d5-11e9-817a-8b6d0ee42cc0.gif)

**Comment by w4mxl** [comment]
@aagarwal1012 Can you consider fixing this problem? Thanks.

**Comment by AadumKhor** [comment]
Hi @sooxt98 . I am unable to replicate this. I have tried `ListView.builder`, `ListView` and also `CustomScrollView` with `ClampingScrollPhysics` and none of them seem to have a problem. 

Closing this issue.

**Comment by sooxt98** [comment]
@AadumKhor try to scroll up and instantly scroll down

**Comment by AadumKhor** [comment]
This is the code I am testing with. You can test it yourself by removing `StreamBuilder` from the tree.

```
    return Scaffold(
        appBar: new AppBar(
          title: Text('Example App'),
        ),
        body: LiquidPullToRefresh(
          onRefresh: _handleRefresh,
          springAnimationDurationInMilliseconds: 1000,
          child: StreamBuilder<int>(
              stream: counterStream,
              builder: (context, snapshot) {
                return ListView.builder(
                    itemCount: _items.length,
                    physics: ClampingScrollPhysics(),
                    itemBuilder: (context, index) {
                      return ListTile(
                        title: Text(_items[index]),
                        subtitle: Text(snapshot.data.toString()),
                      );
                    });
              }),
        ));
```
This is the result on the emulator. 
![clampin_gif_1](https://user-images.githubusercontent.com/37381075/80691504-fd504580-8aed-11ea-97ed-936d4fe6db0d.gif)

Replacing the `LiquidPullToRefresh` with `RefreshIndicator` the result is this.

![clampin_gif_2](https://user-images.githubusercontent.com/37381075/80691845-6e8ff880-8aee-11ea-8d97-9cd97242ec95.gif)

The behavior seems to be almost identical. They first clamp the scroll and on second drag the refresh part comes in. 

If you have the code you tested this on please mention it here so that I can further understand the issue.

**Comment by sooxt98** [comment]
Hi @AadumKhor 
In this case , is diff ; its iOS behaviour that sometimes makes user cant trigger the pull to refresh . As u can see in that gif, I can simply keep pulling down the card without triggering the pulltorefresh
