### ISSUE TITLE
Animation customization requests

### ISSUE THREAD

**Issue by SwissCheese5** [aagarwal1012/Liquid-Pull-To-Refresh#33]
- [x] Animation duration when closing the refresh widget should be adjustable (and faster by default)
- [ ] Refreshing should be cancelled if you pulled the screen down, then pulled it back up manually (and shouldn't flatten horizontally)
- [ ] Option to replace the spinning widget with CircularProgressIndicator(value: <parameter or null>)

**Comment by AadumKhor** [comment]
@SwissCheese5 solved first part of this issue in the last merge. Will continue working on it. Changes will be reflected in latest package update. Thank you for your suggestions.

**Comment by AadumKhor** [comment]
@SwissCheese5 we thought about it and did some experiments with the changes you suggested. While working on them we realized that the last two suggestions are not in the scope of the package. I'll explain why.

The second suggestion would make our functionality counter-intuitive since after the refresh initiates, our app should wait for that to finish, it should not be interrupted. On top of this, Flutter's built in `RefreshIndicator` does not support cancelling the refresh once it has begun on screen. With that as a standard we decided not to move forward with this. 

We experimented with the possibility of having the built in `CircularProgressIndicator` instead of our custom built indicator. It simply does not match the essence of the package and looks out of place. 

Since the only suggestion this issue had has been resolved in recent commits, I think we should close this now.  Feel free to add something to this and reopen the issue if you think it is necessary. Thanks.
