### ISSUE TITLE
Scroll to load more function (pagination) please

### ISSUE THREAD

**Issue by williamSalmon** [aagarwal1012/Liquid-Pull-To-Refresh#35]
Nice widget! Any chance you can add a scroll to load more functionality? Thanks

**Comment by AadumKhor** [comment]
@williamSalmon Thanks for the suggestion. Our package is an extension to the built in `RefreshIndicator` and not the general ProgressIndicators we have in Flutter. From what I get from your request is that you would want "scroll to load more" type of thing with this package, that however would be against the essence of the package since this is used for refresh and not loading in general. Please correct me if I have the wrong impression, looking forward to know more about this.
